theme: architect
@@ -10,7 +10,7 @@ jobs:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          ruby-version: 3.2.0
          bundler-cache: true
      - name: build
        run: script/bootstrap
